"""
389 Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
import collections
class Solution:
    # OJ best solution
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return list(collections.Counter(t) - collections.Counter(s))[0]
    # my own solution
    def findTheDifference2(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        c1, c2 = set(s), set(t)
        c3 = c2.difference(c1)
        if c3:
            return c3.pop()
        else:
            return [c for c in c1 if s.count(c) != t.count(c)][0]

s = "abcd"
t = "abcdb"
obj = Solution()
print(obj.findTheDifference(s,t))